version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/workspace/src
      - ./pom.xml:/workspace/pom.xml
      - maven-repo:/workspace/.m2
    environment:
      - MAVEN_OPTS=-Dmaven.repo.local=/workspace/.m2
    develop:
      watch:
        - action: sync
          path: ./src/main/resources/static
          target: /workspace/src/main/resources/static
          ignore:
            - target/
        - action: sync
          path: ./src/main/resources/templates
          target: /workspace/src/main/resources/templates
          ignore:
            - target/
        - action: rebuild
          path: ./src/main/java
          target: /workspace/src/main/java
          ignore:
            - target/
        - action: rebuild
          path: ./pom.xml
          target: /workspace/pom.xml

  postgres:
    image: postgres:14-alpine
    container_name: jolt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: jolt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  maven-repo:
    driver: local
